name: Mend (WhiteSource) Scan

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  scan:
    name: Scan Runner
    if: github.repository == 'trimble-oss/modus-icons'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run Scan Action
        uses: trimble-oss/gh-actions/mend-scanner@main

        with:
          apiKey: ${{ secrets.WSS_API_KEY }}
          configFile: "wss-unified-agent.config"
