name: Release notes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    if: github.repository == 'trimblemaps/modus-icons'

    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
