name: Review reminders

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  deploy:
    name: Review reminders
    if: github.repository == 'trimble-oss/modus-icons'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: blombard/review-reminder@ce62729930ad100cd5058bfca9d87da66217c981 # master
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          reminder-comment: "Don't forget to review this PR !"
          days-before-reminder: "5"
