name: Review reminders

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  deploy:
    name: Review reminders
    if: github.repository == 'trimble-oss/modus-icons'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: blombard/review-reminder@68327537d348d21ff08b58e52b1e323eff9c8686 # master
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          reminder-comment: "Don't forget to review this PR !"
          days-before-reminder: "5"
