name: SonarQube Scan

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 20

permissions:
  contents: read

jobs:
  scan:
    name: Sonar Scan Runner
    if: ${{ github.actor != 'dependabot' && github.repository == 'trimble-oss/modus-icons' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Sonar Scan Action
        uses: sonarsource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
